name: morpheusai-ponder-monorepo
region: nyc1

alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED

databases:
- cluster_name: morpheusai-ponder-postgres
  db_name: ponder_production
  db_user: ponder_user
  engine: PG
  name: ponder-db
  production: true
  version: "15"

services:
# PostgreSQL database connection info is automatically injected as DATABASE_URL

# Ponder Builders Service - Handles Arbitrum & Base chains
- name: ponder-builders
  source_dir: apps/ponder-builders
  github:
    repo: MorpheusAIs/ponder-builders-index
    branch: main
  build_command: |
    cd /workspace
    npm install
    npm run build --workspace=packages/shared-abis
    npm run build --workspace=apps/ponder-builders
  run_command: npm run start --workspace=apps/ponder-builders
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: professional-xs  # 1 vCPU, 1 GB RAM
  http_port: 42069
  routes:
  - path: /builders
    preserve_path_prefix: true
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production
  - key: DATABASE_SCHEMA
    value: ponder_builders_${APP_DOMAIN_HASH}
  - key: VIEWS_SCHEMA
    value: ponder_builders_latest
  - key: PONDER_LOG_LEVEL
    value: info
  - key: PONDER_RPC_URL_42161
    value: ${ARBITRUM_RPC_URL}
    type: SECRET
  - key: PONDER_RPC_URL_8453
    value: ${BASE_RPC_URL}
    type: SECRET

# Ponder Capital Service - Handles Ethereum mainnet & Arbitrum capital flows
- name: ponder-capital
  source_dir: apps/ponder-capital
  github:
    repo: MorpheusAIs/ponder-builders-index
    branch: main
  build_command: |
    cd /workspace
    npm install
    npm run build --workspace=packages/shared-abis
    npm run build --workspace=apps/ponder-capital
  run_command: npm run start --workspace=apps/ponder-capital
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: professional-xs  # 1 vCPU, 1 GB RAM
  http_port: 42069
  routes:
  - path: /capital
    preserve_path_prefix: true
  health_check:
    http_path: /health
    initial_delay_seconds: 60  # Capital service needs more time for mainnet sync
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production
  - key: DATABASE_SCHEMA
    value: ponder_capital_${APP_DOMAIN_HASH}
  - key: VIEWS_SCHEMA
    value: ponder_capital_latest
  - key: PONDER_LOG_LEVEL
    value: info
  - key: PONDER_RPC_URL_1
    value: ${ETHEREUM_RPC_URL}
    type: SECRET
  - key: PONDER_RPC_URL_42161
    value: ${ARBITRUM_RPC_URL}
    type: SECRET

# Apollo Federation Gateway - GraphQL API aggregation
- name: apollo-gateway
  source_dir: gateway/apollo-federation
  github:
    repo: MorpheusAIs/ponder-builders-index
    branch: main
  build_command: |
    cd /workspace
    npm install
    npm run build --workspace=gateway/apollo-federation
  run_command: npm run start --workspace=gateway/apollo-federation
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs  # 0.5 vCPU, 0.5 GB RAM
  http_port: 4000
  routes:
  - path: /graphql
    preserve_path_prefix: false
  - path: /
  health_check:
    http_path: /health
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production
  - key: PONDER_BUILDERS_ENDPOINT
    value: ${ponder-builders.PRIVATE_URL}/graphql
  - key: PONDER_CAPITAL_ENDPOINT
    value: ${ponder-capital.PRIVATE_URL}/graphql
  - key: APOLLO_GRAPH_VARIANT
    value: production

# Read-only SQL API Service (Optional scaling service)
- name: ponder-sql-api
  source_dir: apps/ponder-builders  # Can serve both builders and capital
  github:
    repo: MorpheusAIs/ponder-builders-index
    branch: main
  build_command: |
    cd /workspace
    npm install
    npm run build --workspace=packages/shared-abis
    npm run build --workspace=apps/ponder-builders
  run_command: npx ponder serve --schema=ponder_builders_latest
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs  # 0.5 vCPU, 0.5 GB RAM
  http_port: 42069
  routes:
  - path: /sql
    preserve_path_prefix: true
  health_check:
    http_path: /health
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production
  - key: PONDER_LOG_LEVEL
    value: info

# Jobs for database maintenance
jobs:
- name: db-create-views-builders
  source_dir: apps/ponder-builders
  github:
    repo: MorpheusAIs/ponder-builders-index
    branch: main
  build_command: |
    cd /workspace
    npm install
    npm run build --workspace=packages/shared-abis
    npm run build --workspace=apps/ponder-builders
  run_command: npx ponder db create-views --schema=ponder_builders_${APP_DOMAIN_HASH} --views-schema=ponder_builders_latest
  environment_slug: node-js
  instance_size_slug: basic-xxs
  kind: POST_DEPLOY
  envs:
  - key: NODE_ENV
    value: production

- name: db-create-views-capital
  source_dir: apps/ponder-capital
  github:
    repo: MorpheusAIs/ponder-builders-index
    branch: main
  build_command: |
    cd /workspace
    npm install
    npm run build --workspace=packages/shared-abis
    npm run build --workspace=apps/ponder-capital
  run_command: npx ponder db create-views --schema=ponder_capital_${APP_DOMAIN_HASH} --views-schema=ponder_capital_latest
  environment_slug: node-js
  instance_size_slug: basic-xxs
  kind: POST_DEPLOY
  envs:
  - key: NODE_ENV
    value: production

# Static site for documentation/dashboard (optional)
static_sites:
- name: docs
  source_dir: docs
  github:
    repo: MorpheusAIs/ponder-builders-index
    branch: main
  build_command: |
    echo "Building static documentation site"
    mkdir -p _site
    cp -r . _site/
  output_dir: _site
  routes:
  - path: /docs
