# PostgreSQL Exporter for Ponder Database Monitoring
# Extends the main monitoring stack with database-specific metrics

version: '3.8'

services:
  # PostgreSQL Exporter - Database metrics
  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    container_name: ponder_postgres_exporter
    restart: unless-stopped
    ports:
      - "9187:9187"
    environment:
      # Connection configuration (adjust based on your setup)
      - DATA_SOURCE_NAME=postgresql://ponder_user:${POSTGRES_PASSWORD}@${DATABASE_HOST:-ponder-db}:5432/ponder_production?sslmode=disable
      
      # Metrics configuration
      - PG_EXPORTER_EXTEND_QUERY_PATH=/etc/postgres_exporter/queries.yaml
      - PG_EXPORTER_INCLUDE_DATABASES=ponder_production,ponder_builders_latest,ponder_capital_latest
      - PG_EXPORTER_EXCLUDE_DATABASES=template0,template1
      - PG_EXPORTER_AUTO_DISCOVER_DATABASES=true
      - PG_EXPORTER_WEB_LISTEN_ADDRESS=:9187
      - PG_EXPORTER_WEB_TELEMETRY_PATH=/metrics
      - PG_EXPORTER_LOG_LEVEL=info
      
    volumes:
      - ./postgres-exporter/queries.yaml:/etc/postgres_exporter/queries.yaml:ro
    networks:
      - monitoring
      - ponder
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9187/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - prometheus

networks:
  monitoring:
    external: true
  ponder:
    external: true
