version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ponder_builders
      POSTGRES_USER: ponder
      POSTGRES_PASSWORD: ponder_dev_password
      POSTGRES_MULTIPLE_DATABASES: ponder_builders,ponder_capital,ponder_subnets
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ponder -d ponder_builders"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Optional: Redis for caching (future use)
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Optional: Grafana for monitoring
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    profiles:
      - monitoring

volumes:
  postgres_data:
  redis_data:
  grafana_data:
